import React, { useEffect, useState, type FormEvent } from 'react'
import type { AdminOverview, CreateAdminUserInput } from '../../data/adminRepository'
import { Icon } from '../shared/Icon'
import { FormField } from '../shared/FormField'
import { ModalHeader } from '../shared/ModalHeader'
import { ModalShell } from '../shared/ModalShell'

type Tab = 'personal' | 'professional' | 'access' | 'address' | 'rh'
type Option = { id: string; name: string }

const sensitiveEmployeeFields = ['cpf', 'rg', 'emitterOrgan', 'birthDate', 'maritalStatus', 'phone', 'personalEmail', 'emergencyContactName', 'emergencyContactPhone', 'zipCode', 'street', 'number', 'complement', 'neighborhood', 'city', 'state', 'country']

export function AdminUserDialog({ roles, departments = [], positions = [], levels = [], users = [], canSetSalary = false, canEditSensitive = false, onClose, onCreate }: { roles: AdminOverview['roles']; departments?: Option[]; positions?: Option[]; levels?: Option[]; users?: Option[]; canSetSalary?: boolean; canEditSensitive?: boolean; onClose: () => void; onCreate: (input: CreateAdminUserInput) => Promise<void> }) {
  const [tab, setTab] = useState<Tab>(canEditSensitive ? 'personal' : 'professional')
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [username, setUsername] = useState(''); const [initialPassword, setInitialPassword] = useState(''); const [selectedRoles, setSelectedRoles] = useState<string[]>(['specialist']); const [error, setError] = useState(''); const [isSaving, setIsSaving] = useState(false)
  const [employee, setEmployee] = useState<Record<string, string>>({ departmentId: '', positionId: '', professionalLevelId: '', managerId: '', status: 'active', contractType: 'CLT', workModality: 'hibrido', monthlyHours: '220', country: 'Brasil' })
  useEffect(() => { if (!employee.departmentId && departments[0]) setEmployee((current) => ({ ...current, departmentId: departments[0].id })) }, [departments, employee.departmentId])
  const set = (key: string) => (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => setEmployee((current) => ({ ...current, [key]: event.target.value }))
  function toggleRole(code: string) { setSelectedRoles((current) => current.includes(code) ? current.length === 1 ? current : current.filter((item) => item !== code) : current.length >= 5 ? current : [...current, code]) }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setIsSaving(true); setError(''); const allowedEmployee = canEditSensitive ? employee : Object.fromEntries(Object.entries(employee).filter(([key]) => !sensitiveEmployeeFields.includes(key))); try { await onCreate({ name: name.trim(), email: email.trim(), username: username.trim(), roles: selectedRoles, initialPassword, department: employee.departmentId, status: employee.status === 'active' ? 'active' : 'inactive', employee: allowedEmployee }); onClose() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível salvar o colaborador.') } finally { setIsSaving(false) } }
  const tabs: Array<[Tab, string]> = [
    ...(canEditSensitive ? [['personal', 'PESSOAL'] as [Tab, string]] : []),
    ['professional', 'PROFISSIONAL'], ['access', 'ACESSO'],
    ...(canEditSensitive ? [['address', 'ENDEREÇO'] as [Tab, string]] : []),
    ['rh', 'RH'],
  ]
  return <ModalShell accessibleTitle="Novo colaborador" onClose={onClose} size="lg"><form className="employee-create-dialog" onSubmit={submit}><ModalHeader closeLabel="Fechar cadastro de colaborador" eyebrow="CADASTRO COMPLETO DE COLABORADOR" icon={<Icon name="people" size={21} />} onClose={onClose} title={<>Quem vai tornar<br /><em>possível?</em></>} /><div className="employee-tabs" role="tablist" aria-label="Seções do cadastro de colaborador">{tabs.map(([id, label]) => <button key={id} type="button" role="tab" aria-selected={tab === id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}>{label}</button>)}</div><div className="employee-create-dialog__body">
    {tab === 'personal' && <div className="employee-form-grid"><FormField controlId="employee-name" label="NOME COMPLETO" required><input autoFocus value={name} onChange={(e) => setName(e.target.value)} required /></FormField><FormField controlId="employee-social-name" label="NOME SOCIAL"><input value={employee.socialName || ''} onChange={set('socialName')} /></FormField><FormField controlId="employee-cpf" label="CPF"><input value={employee.cpf || ''} onChange={set('cpf')} /></FormField><FormField controlId="employee-rg" label="RG"><input value={employee.rg || ''} onChange={set('rg')} /></FormField><FormField controlId="employee-emitter" label="ÓRGÃO EMISSOR"><input value={employee.emitterOrgan || ''} onChange={set('emitterOrgan')} /></FormField><FormField controlId="employee-birth" label="DATA DE NASCIMENTO"><input type="date" value={employee.birthDate || ''} onChange={set('birthDate')} /></FormField><FormField controlId="employee-marital" label="ESTADO CIVIL"><input value={employee.maritalStatus || ''} onChange={set('maritalStatus')} /></FormField><FormField controlId="employee-phone" label="TELEFONE"><input value={employee.phone || ''} onChange={set('phone')} /></FormField><FormField controlId="employee-personal-email" label="E-MAIL PESSOAL"><input type="email" value={employee.personalEmail || ''} onChange={set('personalEmail')} /></FormField><FormField controlId="employee-emergency-name" label="CONTATO DE EMERGÊNCIA"><input value={employee.emergencyContactName || ''} onChange={set('emergencyContactName')} /></FormField><FormField controlId="employee-emergency-phone" label="TELEFONE DE EMERGÊNCIA"><input value={employee.emergencyContactPhone || ''} onChange={set('emergencyContactPhone')} /></FormField></div>}
    {tab === 'professional' && <div className="employee-form-grid">{!canEditSensitive && <FormField controlId="employee-name" label="NOME COMPLETO" required><input autoFocus value={name} onChange={(e) => setName(e.target.value)} required /></FormField>}<FormField controlId="employee-department" label="DEPARTAMENTO" required><select value={employee.departmentId} onChange={set('departmentId')} required><option value="">Selecione</option>{departments.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></FormField><FormField controlId="employee-position" label="CARGO"><select value={employee.positionId} onChange={set('positionId')}><option value="">Selecione</option>{positions.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></FormField><FormField controlId="employee-level" label="NÍVEL"><select value={employee.professionalLevelId} onChange={set('professionalLevelId')}><option value="">Selecione</option>{levels.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></FormField><FormField controlId="employee-manager" label="GESTOR"><select value={employee.managerId} onChange={set('managerId')}><option value="">Sem gestor</option>{users.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></FormField><FormField controlId="employee-admission" label="DATA DE ADMISSÃO"><input type="date" value={employee.admissionDate || ''} onChange={set('admissionDate')} /></FormField><FormField controlId="employee-contract" label="VÍNCULO"><select value={employee.contractType} onChange={set('contractType')}><option value="CLT">CLT</option><option value="PJ">PJ</option><option value="estagio">Estágio</option><option value="freelancer">Freelancer</option><option value="temporario">Temporário</option><option value="outro">Outro</option></select></FormField></div>}
    {tab === 'access' && <div className="employee-form-grid"><FormField controlId="employee-email" label="E-MAIL PROFISSIONAL" required><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></FormField><FormField controlId="employee-password" label="SENHA INICIAL" hint="Mínimo de 12 caracteres." required><input type="password" minLength={12} value={initialPassword} onChange={(e) => setInitialPassword(e.target.value)} required /></FormField><FormField controlId="employee-login" label="LOGIN"><input value={username} onChange={(e) => setUsername(e.target.value)} /></FormField><FormField controlId="employee-status" label="STATUS"><select value={employee.status} onChange={set('status')}><option value="active">Ativo</option><option value="inactive">Inativo</option></select></FormField><div className="employee-role-field"><span>CARGOS E PERMISSÕES</span><div className="admin-role-picker">{roles.map((item) => <button className={selectedRoles.includes(item.code) ? 'selected' : ''} type="button" key={item.code} aria-pressed={selectedRoles.includes(item.code)} onClick={() => toggleRole(item.code)}><i>{selectedRoles.includes(item.code) ? '✓' : '+'}</i><span><b>{item.name}</b><small>{item.permissionCount} permissões</small></span></button>)}</div></div></div>}
    {tab === 'address' && <div className="employee-form-grid">{[['zipCode','CEP'],['street','LOGRADOURO'],['number','NÚMERO'],['complement','COMPLEMENTO'],['neighborhood','BAIRRO'],['city','CIDADE'],['state','UF']].map(([key,label]) => <FormField key={key} controlId={`employee-${key}`} label={label}><input maxLength={key === 'state' ? 2 : undefined} value={employee[key] || ''} onChange={set(key)} /></FormField>)}</div>}
    {tab === 'rh' && <div className="employee-form-grid"><FormField controlId="employee-modality" label="MODALIDADE"><select value={employee.workModality} onChange={set('workModality')}><option value="hibrido">Híbrido</option><option value="remoto">Remoto</option><option value="presencial">Presencial</option></select></FormField>{canSetSalary && <><FormField controlId="employee-salary" label="REMUNERAÇÃO INICIAL"><input type="number" min="0" value={employee.salary || ''} onChange={set('salary')} /></FormField><FormField controlId="employee-hours" label="HORAS MENSAIS"><input type="number" min="1" value={employee.monthlyHours} onChange={set('monthlyHours')} /></FormField></>}<FormField controlId="employee-notes" label="OBSERVAÇÕES"><textarea value={employee.notes || ''} onChange={set('notes')} /></FormField></div>}
    {error && <p className="employee-dialog-error" role="alert">{error}</p>}<button className="employee-dialog-submit" type="submit" disabled={isSaving}>{isSaving ? 'SALVANDO…' : <>CRIAR COLABORADOR <span>→</span></>}</button></div></form></ModalShell>
}
